### ISSUE TITLE
Add an option for a transparent background.

### ISSUE THREAD

**Issue by ainmosni** [nanotech/jellybeans.vim#34]
I love the theme but I would love it even more if it had the option for a transparent background.

**Comment by Lekensteyn** [comment]
This does not work when `set t_Co=256` is set. Setting `hi Normal ctermbg=NONE` works for the text, but the newlines are still black. Is it possible to have a variable for this?

**Comment by nanotech** [comment]
@Lekensteyn By newlines, do you mean `listchars`' `eol`? What terminal emulator are you using? Could you post a screenshot?

**Comment by Lekensteyn** [comment]
Oh, I meant the *line numbers*, not *new lines*. I am using Konsole on KDE.

Here is a screenshot comparing the jellybean theme (with the `hi Normal ctermbg=NONE` option) with the default vim theme:
![default color theme vs jellybeans](https://cloud.githubusercontent.com/assets/164530/7192243/16010d72-e494-11e4-914f-aef309a009ff.png)

Issues:

 - Background color of line numbers and the current line are invisible.
 - `set colorcolumn=+1` (since vim 7.3) is displayed black.

The latter is a different issue, but it is also visible on the picture.

**Comment by nanotech** [comment]
Ah, I see what's happening. For the line numbers, you need to set `let g:jellybeans_background_color_256='NONE'` instead of plain `hi Normal ctermbg=NONE`, because jellybeans uses that background color in more than once place (as you've seen). Make sure it's set before `colorscheme jellybeans` is called in your `.vimrc`.

For the missing `colorcolumn`, I just tested this myself and apparently Konsole considers the `0` and `16` [cterm color indexes][1] to mean "no color" when your Konsole background color is exactly `#000000`. None of gnome-terminal, OS X Terminal.app, or iTerm 2 do this. Setting your background color to anything else, even just `#000001`, seems to avoid this and makes these colors show up correctly.

As for *why* jellybeans has a solid background color by default, it actually doesn't on OS X terminals (where I originally designed it). Konsole and gnome-terminal (at least) only make the default background transparent and other background colors are opaque, but the OS X terminals apply transparency to all background colors:

![Transparent jellybeans backgrounds on OS X](https://cloud.githubusercontent.com/assets/34699/7193269/965ca474-e45b-11e4-8768-482e936efe17.png)

Maybe I'll change the default to get this working better for Linux users.

[1]: https://github.com/guns/xterm-color-table.vim

**Comment by Lekensteyn** [comment]
I forgot to mention that setting `g:jellybeans_background_color_256='NONE'` has no affect when `set t_Co=256` is set. This happens with vim-jellybeans 1.5-1 and vim 7.4.663-2 on Arch Linux.

**Comment by nanotech** [comment]
Oh right, 1.5 doesn't have that option yet. Could you try the latest version from git?

**Comment by Lekensteyn** [comment]
v1.5-29-gf931895 fixes the transparency issue for line numbers. The color column is still invisible with 000001 and even 000030. 500000 results in a solid background line though.
