### ISSUE TITLE
Font?

### ISSUE THREAD

**Issue by LikiPiki** [nanotech/jellybeans.vim#52]
What font you use in this screenshot?

**Comment by sliceofcode** [comment]
The font uses the embedded bitmap (automatically used if enabled at 10px) in the font Monaco.

Because I also wanted the nice looking bitmaps, I downloaded the font here (not my link):
- http://www.gringod.com/wp-upload/software/Fonts/Monaco_Linux.ttf

Then, I had to remove `82-no-embedded-bitmaps.conf` from `/etc/fonts/conf.d` in order to enable embedded bitmaps:
```sh
$ sudo rm /etc/fonts/conf.d/82-no-embedded-bitmaps.conf
````
Note that removing the file may have unintended side effects in some fonts.

Contents of `82-no-embedded-bitmaps.conf`:
```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>

  <!-- Use embedded bitmaps in fonts like Calibri? -->
  <match target="font" >
    <edit name="embeddedbitmap" mode="assign">
      <bool>false</bool>
    </edit>
  </match>

</fontconfig>
```

Then, update the font cache and use it in your terminal:
```sh
$ sudo fc-cache -fv
```

- Example of config for URXVT
`~/.Xdefaults`
```
URxvt*font: xft:Monaco:pixelsize=10:antialias=false
```

**Comment by LikiPiki** [comment]
Thanks a lot)
