### ISSUE TITLE
broken on colorstepper

### ISSUE THREAD

**Issue by kevinlawler** [nanotech/jellybeans.vim#84]
displays long error list when reached in cycle of colorschemes

https://github.com/qualiabyte/vim-colorstepper

**Comment by nanotech** [comment]
Looks like vim-colorstepper [uses `:source` to load colorschemes](https://github.com/qualiabyte/vim-colorstepper/blob/a39875454b866fe751482b3ceb17f47ffb3c5da7/colorstepper.vim#L21) instead of `:colorscheme`. Vim probably does some extra setup in `:colorscheme` that makes Jellybeans load correctly.

Since `:colorscheme` is the intended way to load color schemes in Vim, vim-colorstepper should probably be changed to use it instead.
